export interface IEntityLink {
  rel: string;
  href: string;
}

export interface IEntity {
  id: number;
  name: string;
  entities_id: number | null;
  completename: string;
  comment: string | null;
  level: number;
  sons_cache: any | null;
  ancestors_cache: any | null;
  registration_number: string | null;
  address: string | null;
  postcode: string | null;
  town: string | null;
  state: string | null;
  country: string | null;
  website: string | null;
  phonenumber: string | null;
  fax: string | null;
  email: string | null;
  admin_email: string | null;
  admin_email_name: string | null;
  from_email: string | null;
  from_email_name: string | null;
  noreply_email: string | null;
  noreply_email_name: string | null;
  replyto_email: string | null;
  replyto_email_name: string | null;
  notification_subject_tag: string | null;
  ldap_dn: string | null;
  tag: string | null;
  authldaps_id: number;
  mail_domain: string | null;
  entity_ldapfilter: string | null;
  mailing_signature: string | null;
  url_base: string | null;
  cartridges_alert_repeat: number;
  consumables_alert_repeat: number;
  use_licenses_alert: number;
  send_licenses_alert_before_delay: number;
  use_certificates_alert: number;
  send_certificates_alert_before_delay: number;
  certificates_alert_repeat_interval: number;
  use_contracts_alert: number;
  send_contracts_alert_before_delay: number;
  use_infocoms_alert: number;
  send_infocoms_alert_before_delay: number;
  use_reservations_alert: number;
  use_domains_alert: number;
  send_domains_alert_close_expiries_delay: number;
  send_domains_alert_expired_delay: number;
  autoclose_delay: number;
  autopurge_delay: number;
  notclosed_delay: number;
  calendars_strategy: number;
  calendars_id: number;
  auto_assign_mode: number;
  tickettype: number;
  max_closedate: string | null;
  inquest_config: number;
  inquest_rate: number;
  inquest_delay: number;
  inquest_URL: string | null;
  inquest_max_rate: number;
  inquest_default_rate: number;
  inquest_mandatory_comment: number;
  max_closedate_change: string | null;
  inquest_config_change: number;
  inquest_rate_change: number;
  inquest_delay_change: number;
  inquest_URL_change: string | null;
  inquest_max_rate_change: number;
  inquest_default_rate_change: number;
  inquest_mandatory_comment_change: number;
  autofill_warranty_date: string;
  autofill_use_date: string;
  autofill_buy_date: string;
  autofill_delivery_date: string;
  autofill_order_date: string;
  tickettemplates_strategy: number;
  tickettemplates_id: number;
  changetemplates_strategy: number;
  changetemplates_id: number;
  problemtemplates_strategy: number;
  problemtemplates_id: number;
  entities_strategy_software: number;
  entities_id_software: number;
  default_contract_alert: number;
  default_infocom_alert: number;
  default_cartridges_alarm_threshold: number;
  default_consumables_alarm_threshold: number;
  delay_send_emails: number;
  is_notif_enable_default: number;
  inquest_duration: number;
  inquest_duration_change: number;
  date_mod: string | null;
  date_creation: string | null;
  autofill_decommission_date: string;
  suppliers_as_private: number;
  anonymize_support_agents: number;
  display_users_initials: number;
  contracts_strategy_default: number;
  contracts_id_default: number;
  enable_custom_css: number;
  custom_css_code: string;
  latitude: number | string | null;
  longitude: number | string | null;
  altitude: number | string | null;
  transfers_strategy: number;
  transfers_id: number;
  agent_base_url: string | null;
  approval_reminder_repeat_interval: number;
  "2fa_enforcement_strategy": number;
  is_contact_autoupdate: number;
  is_user_autoupdate: number;
  is_group_autoupdate: number;
  is_location_autoupdate: number;
  state_autoupdate_mode: number;
  is_contact_autoclean: number;
  is_user_autoclean: number;
  is_group_autoclean: number;
  is_location_autoclean: number;
  state_autoclean_mode: number;
  show_tickets_properties_on_helpdesk: number;
  custom_helpdesk_home_scene_left: string;
  custom_helpdesk_home_scene_right: string;
  custom_helpdesk_home_title: string;
  enable_helpdesk_home_search_bar: number;
  enable_helpdesk_service_catalog: number;
  expand_service_catalog: number;
  links: IEntityLink[];
}
