export interface IUserDefaultEntity {
    id: number;
    name: string;
}

export interface ILink {
    rel: string;
    href: string;
}

export interface IUser {
    id: number;
    name: string | null;
    password_last_update: string | null;
    phone: string | null;
    phone2: string | null;
    mobile: string | null;
    realname: string | null;
    firstname: string | null;
    locations_id: number;
    language: string | null;
    use_mode: number;
    list_limit: number;
    is_active: number;
    comment: string | null;
    auths_id: number;
    authtype: number;
    last_login: string | null;
    date_mod: string | null;
    date_sync: string | null;
    is_deleted: number;
    profiles_id: number;
    entities_id: number;
    usertitles_id: number;
    usercategories_id: number;
    date_format: number | null;
    number_format: number | null;
    names_format: number | null;
    csv_delimiter: string | null;
    is_ids_visible: number | null;
    use_flat_dropdowntree: number | null;
    use_flat_dropdowntree_on_search_result: number | null;
    show_jobs_at_login: number | null;
    priority_1: string | null;
    priority_2: string | null;
    priority_3: string | null;
    priority_4: string | null;
    priority_5: string | null;
    priority_6: string | null;
    followup_private: number | null;
    task_private: number | null;
    default_requesttypes_id: number | null;
    password_forget_token: string | null;
    password_forget_token_date: string | null;
    user_dn: string | null;
    user_dn_hash: string | null;
    registration_number: string | null;
    show_count_on_tabs: number | null;
    refresh_views: number | null;
    set_default_tech: number | null;
    set_followup_tech: number | null;
    set_solution_tech: number | null;
    personal_token_date: string | null;
    api_token_date: string | null;
    cookie_token_date: string | null;
    display_count_on_home: number | null;
    notification_to_myself: number | null;
    duedateok_color: string | null;
    duedatewarning_color: string | null;
    duedatecritical_color: string | null;
    duedatewarning_less: number | null;
    duedatecritical_less: number | null;
    duedatewarning_unit: string | null;
    duedatecritical_unit: string | null;
    is_deleted_ldap: number;
    pdffont: string | null;
    picture: string | null;
    begin_date: string | null;
    end_date: string | null;
    keep_devices_when_purging_item: number | null;
    privatebookmarkorder: string | null;
    backcreated: number | null;
    task_state: number | null;
    planned_task_state: number | null;
    palette: string | null;
    page_layout: string | null;
    fold_menu: number | null;
    savedsearches_pinned: string | null;
    timeline_order: string | null;
    itil_layout: string | null;
    richtext_layout: string | null;
    set_default_requester: number | null;
    lock_autolock_mode: number | null;
    lock_directunlock_notification: number | null;
    date_creation: string | null;
    highcontrast_css: number | null;
    plannings: string | null;
    sync_field: string | null;
    groups_id: number;
    users_id_supervisor: number;
    timezone: string | null;
    default_dashboard_central: number | null;
    default_dashboard_assets: number | null;
    default_dashboard_helpdesk: number | null;
    default_dashboard_mini_ticket: number | null;
    default_central_tab: number | null;
    nickname: string | null;
    substitution_end_date: string | null;
    substitution_start_date: string | null;
    toast_location: number | null;
    timeline_action_btn_layout: string | null;
    timeline_date_format: string | null;
    "2fa_unenforced": number;
    is_notif_enable_default: number | null;
    show_search_form: number | null;
    search_pagination_on_top: number | null;
    links: ILink[];

    // Keeping optional previous fields in case they are populated locally or via other endpoints
    username?: string;
    emails?: string[]; 
    location?: string | null;
    default_profile?: string | null; 
    default_entity?: IUserDefaultEntity | null;
    title?: string | null;
    category?: string | null;
}
